---
- include: directories.yml

- name: Nginx - Install build requirements
  become: yes
  apt: name={{ item }} update_cache=yes
  with_items:
    - build-essential
    - zlib1g-dev
    - libpcre3
    - libpcre3-dev
    - unzip

- name: Nginx - Download Nginx source
  get_url:
    url: "{{nginx_source_url}}"
    dest: "{{ nginx_build_tmp_dir }}/nginx-{{nginx_source_version}}.tar.gz"

- include: "modules.yml"

- name: Nginx - Unpack Nginx source
  command: tar -xvzf {{ nginx_build_tmp_dir }}/nginx-{{nginx_source_version}}.tar.gz
           chdir={{ nginx_build_tmp_dir }} creates={{ nginx_build_tmp_dir }}/nginx-{{nginx_source_version}}/README

- name: Nginx - kill nginx
  command: pkill nginx
  ignore_errors: yes

- name: Nginx - Make Nginx source (Grab lunch . . .)
  shell: >
    cd {{ nginx_build_tmp_dir }}/nginx-{{nginx_source_version}} &&
    ./configure {{nginx_source_flags}} &&
    make &&
    sudo make install

- name: Nginx - Update the sym link
  file:
    path: "{{ nginx_bin }}"
    src: "{{ nginx_source_sbin_path }}"
    state: link
    force: yes

- name: Nginx - Checkout nginx-sysvinit-script
  git:
    repo: https://github.com/Fleshgrinder/nginx-sysvinit-script.git
    dest: "{{ nginx_build_tmp_dir }}/nginx-sysvinit-script"
    update: no

- name: Nginx - Write nginx.service
  template:
    src: nginx.service.j2
    dest: "/lib/systemd/system/nginx.service"

- name: Nginx - Create Init Scripts (LSB /etc/init.d/nginx & /etc/default/nginx)
  command: sudo make
  become: yes
  args:
    chdir: "{{ nginx_build_tmp_dir }}/nginx-sysvinit-script"

- name: Nginx - Enable Nginx service
  service:
    name: nginx
    enabled: yes
  notify: restart_nginx